name: ⭐️ Accessibility
description: アクセシビリティ改善の提案
title: "[A11y] "
labels: ["⭐️ アクセシビリティ"]
body:
  - type: textarea
    id: description
    attributes:
      label: 内容
      description: アクセシビリティの問題と改善案を教えてください
      placeholder: |
        【問題】


        【改善案】

    validations:
      required: true
