name: 🐛 Bug Report
description: バグや問題を報告する
title: '[Bug] '
labels: ['🐛 バグ']
body:
  - type: textarea
    id: description
    attributes:
      label: 内容
      description: 何が起きて、どうなるべきか教えてください
      placeholder: |
        【発生した問題】


        【期待する動作】

    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット（任意）
      description: あれば画像をドラッグ&ドロップ
