name: 🚢 Challenge
description: 主がやったことなくて知見がないIssue
title: "[Challenge] "
labels: ["🚢 チャレンジ"]
body:
  - type: textarea
    id: description
    attributes:
      label: 内容
      description: 何にチャレンジしたいか教えてください
      placeholder: |
        【やりたいこと】


        【なぜチャレンジングか】

    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: 参考資料（任意）
      description: 参考になりそうなURLがあれば
