name: 📈 Efficiency
description: 効率化のためのIssue
title: "[Efficiency] "
labels: ["📈 効率化"]
body:
  - type: textarea
    id: description
    attributes:
      label: 内容
      description: 何をどう効率化したいか教えてください
      placeholder: |
        【対象】


        【改善案】

    validations:
      required: true
