name: 👍 Good First Issue
description: 初めてコントリビュートするのに向いているIssue
title: "[Good First Issue] "
labels: ["👍 Good First Issue"]
body:
  - type: textarea
    id: description
    attributes:
      label: 内容
      description: 何を実装・修正するか教えてください
    validations:
      required: true

  - type: textarea
    id: hints
    attributes:
      label: ヒント（任意）
      description: 参考になる情報があれば
