name: 📚 Library
description: ライブラリが絡むIssue（ライブラリアップデートなど）
title: "[Library] "
labels: ["📚 ライブラリ"]
body:
  - type: textarea
    id: description
    attributes:
      label: 内容
      description: ライブラリの追加・更新・削除など
      placeholder: |
        【ライブラリ名】


        【理由】

    validations:
      required: true
