name: 💬 Question
description: 質問やサポートを求める
title: '[Question] '
labels: ['💭 質問']
body:
  - type: textarea
    id: description
    attributes:
      label: 質問内容
      description: 知りたいこと、困っていることを教えてください
    validations:
      required: true
