name: 🔍 SEO
description: SEO関連のIssue
title: "[SEO] "
labels: ["🔍 SEO"]
body:
  - type: textarea
    id: description
    attributes:
      label: 内容
      description: SEOの何をどう改善したいか教えてください
      placeholder: |
        【対象】


        【改善案】

    validations:
      required: true
