name: ⚙️ Settings
description: 設定まわりのIssue（Githubなど）
title: '[Settings] '
labels: ['⚙️ Settings']
body:
  - type: textarea
    id: description
    attributes:
      label: 内容
      description: 何の設定をどう変更したいか教えてください
      placeholder: |
        【対象】


        【変更案】

    validations:
      required: true
