name: 🎨 UI/UX
description: UI/UXに関するIssue
title: "[UI/UX] "
labels: ["🎨 UI/UX"]
body:
  - type: textarea
    id: description
    attributes:
      label: 内容
      description: 何をどう改善したいか教えてください
      placeholder: |
        【対象】


        【改善案】

    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット（任意）
      description: あれば画像をドラッグ&ドロップ
