name: Entry Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [develop, main]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  code-quality:
    uses: ./.github/workflows/job-biome-check.yaml

  unit-test:
    uses: ./.github/workflows/job-unit-test.yaml

  e2e-test:
    uses: ./.github/workflows/job-e2e-test.yaml
    secrets: inherit

  build-check:
    uses: ./.github/workflows/job-build-check.yaml
    secrets: inherit

  build-storybook:
    uses: ./.github/workflows/job-build-storybook.yaml

  lighthouse:
    uses: ./.github/workflows/job-lighthouse.yaml
    secrets: inherit

  zap-scan:
    uses: ./.github/workflows/job-zap-scan.yaml
    secrets: inherit
